on:
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Metrics Server Config Sync
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - id: sync
        uses: timam/actions/url-file-syncer@main
        with:
          file_url: 'https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml'
          file_path: 'configs/metrics-server.yaml'
      - name: Get the output message
        run: echo "${{ steps.sync.outputs.message }}"

      - name: Commit changes
        if: steps.sync.outputs.message == 'successfully synced local file with remote'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: metrics-server got updates
          create_branch: true
          branch: robot/metrics-server-update
          commit_user_name: Github Robot
          commit_user_email: gitub-robot@timam.io
          file_pattern: 'configs/metrics-server.yaml'
          push_options: '--force'

      - name: Create Pull Request
        if: steps.sync.outputs.message == 'successfully synced local file with remote'
        uses: peter-evans/create-pull-request@v5
        with:
          title: Metrics Server config file got new changes

